### ISSUE TITLE
Tracker: Editing modules and web apps

### ISSUE THREAD

**Issue by xintongxia** [uber/nebula.gl#232]
#### Background 

Geo editing functions are a common interest from both internal and external customers. It is P0 feature on Kepler.gl 2019 [roadmap](https://github.com/uber/kepler.gl/wiki/Kepler.gl-2019-Roadmap#allow-drawing-on-map-to-create-paths-and-polygons--). Also a couple of `react-map-gl` [users](https://github.com/uber/react-map-gl/issues/725) asked for drawing features. 

[Nebula.gl](http://nebula.gl) provides geo editing functionality, but it heavily depends on [`deck.gl`](https://deck.gl/), which may not be suitable for non `deck.gl` use cases, i.e. `react-map-gl` users.

To support both non deck.gl users and non deck.gl use cases, `Nebula.gl` is going to consolidate the efforts from both `nebula.gl` and `react-map-gl` and support deck.gl based editing and svg based editing modules.

#### To Do List 
  - [x] Decouple EditModes from deck.gl and publish `@nebula.gl/edit-modes`
  - [ ] Refactor `Nebula.gl` mode handlers to extend `@nebula.gl/edit-modes` https://github.com/uber/nebula.gl/pull/222
  - [ ] Port ``react-map-gl-draw` from `react-map-gl` and publish `react-map-gl-draw` module https://github.com/uber/nebula.gl/pull/230
  - [ ] Add example app
