### ISSUE TITLE
[Tracker] react-map-gl-draw v1.0

### ISSUE THREAD

**Issue by xintongxia** [uber/nebula.gl#359]
#### Background 
For v1.0

#### To Do List 
  - [ ] Bug fixes (github issues)
  - [ ] Customized modes
  - [ ] Add tests 
  - [ ] Support draw circle
  - [ ] Doc updates
  - [ ] Examples:
    - [ ] A simple example (minimum lines of code)
    - [ ] A example with customized mode
